SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    FLOOR((DAILY_FEE * 30) * (1 - (P.DISCOUNT_RATE / 100))) AS 'FEE'

FROM
    CAR_RENTAL_COMPANY_CAR AS C,
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H,
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P

WHERE
    C.CAR_ID = H.CAR_ID AND
    C.CAR_TYPE = P.CAR_TYPE AND
    (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV') AND
    C.CAR_ID NOT IN (
        SELECT
            C.CAR_ID
        FROM
            CAR_RENTAL_COMPANY_CAR AS C,
            CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
        WHERE
            C.CAR_ID = H.CAR_ID AND
            NOT (H.END_DATE < '2022-11-01' OR H.START_DATE >= '2022-12-01')
    ) AND
    P.DURATION_TYPE = '30일 이상' AND
    500000 <= (DAILY_FEE * 30) * (1 - (P.DISCOUNT_RATE / 100)) AND
    (DAILY_FEE * 30) * (1 - (P.DISCOUNT_RATE / 100)) < 2000000

GROUP BY
    C.CAR_ID

ORDER BY
    FEE DESC,
    C.CAR_TYPE,
    C.CAR_ID DESC